export default function Head(props) {
  return (
    <div>
      <title>Cookie Stand Admin</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </div>
  );
}
