import Head from "next/head";
import { replies } from "/data";
import { useState } from "react";
import Header from "/components/Header.js";
import Footer from "/components/Footer";
import CookieStand from "components/CookieStand";
import ResultsTable from "components/ResultsTable";

export default function Home() {
  const [locations, setLocations] = useState([]);

  function questionAskedHandler(e) {
    e.preventDefault();

    const location = {
      city: e.target.city.value,
      minCustomers: e.target.minCustomers.value,
      maxCustomers: e.target.maxCustomers.value,
      avgCookies: e.target.avgCookies.value,
    };

    setLocations([...locations, city]);
  }

  return (
    <>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="">
        <CookieStand questionAskedHandler={questionAskedHandler} />
        
        <ResultsTable locations={locations} />

      </main>

      <Footer />
    </>
  );
}
